name: Run Terraform Checks
on:
  pull_request:
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@main
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: Secrets found in repository dp-terraform-backend"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Terraform Format
        id: fmt
        run: |
          terraform fmt -check --recursive
          terraform validate
